import os
import subprocess
import time


print(" START CLEANING DNS ")


os.system("sudo /etc/init.d/dns-clean start")
time.sleep(2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.5)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.8)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0*")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1.9)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1.2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.8)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.7)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.6)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.5)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(120)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.5)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.8)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0*")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1.9)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1.2)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(1)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -4 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.8)
os.system("sudo /etc/init.d/dns-clean start")
os.system("sudo ip -6 addr flush label enp2s0")
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.7)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.6)
os.system("sudo /etc/init.d/dns-clean start")
time.sleep(0.5)
os.system("sudo /etc/init.d/dns-clean start")

#INCOMP....


